url: https://www.dustman.me
baseurl: ""

# Site settings
title: Dustman's Website
email: your-email@domain.com
description: "Personal website of Dustman showcasing projects and skills."

# Team names, titles and social links
people:
- name: Dustman
  pic: 1
  position: Developer
  social:
    - title: github
      url: https://github.com/dustman2817

# Social networks usernames
social:
  - title: github
    url: https://github.com/dustman2817

# Postal address (add as many lines as necessary)
address:
  - line: Your Address Line 1
  - line: Your Address Line 2

# Build settings
markdown: kramdown
permalink: pretty