name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      
      - name: Debug Ruby
        run: |
          ruby -v
          gem -v
          which ruby
          which gem
      
      - name: Install dependencies
        run: |
          gem install bundler -v 2.4.22
          bundle -v
          bundle config set --local path 'vendor/bundle'
          bundle config set --local deployment 'true'
          bundle install --jobs 4 --retry 3 --verbose
      
      - name: Debug Jekyll
        run: |
          bundle exec jekyll -v
          bundle exec jekyll doctor
      
      - name: Build site
        run: bundle exec jekyll build --verbose

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 